services:
    app:
        build: .
        ports:
            - "5000:5000"
        environment:
            - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
            - OTEL_LOG_LEVEL=debug
        depends_on:
            - otel-collector

    otel-collector:
        image: otel/opentelemetry-collector-contrib:latest
        command: ["--config=/etc/otel-collector-config.yml"]
        volumes:
            - ./otel-collector-config.yml:/etc/otel-collector-config.yml
        ports:
            - "4320:4318"
            - "8889:8889"

    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus-data:/prometheus
        ports:
            - "9090:9090"

    loki:
        image: grafana/loki:latest
        command: -config.file=/etc/loki/local-config.yml
        ports:
            - "3100:3100"
        volumes:
            - ./loki-config.yml:/etc/loki/local-config.yml
            - loki-data:/loki
        user: "0"

    tempo:
        image: grafana/tempo:latest
        command: ["-config.file=/etc/tempo.yml"]
        ports:
            - "3200:3200"
            - "4317:4317"
            - "4318:4318"
        volumes:
            - ./tempo.yml:/etc/tempo.yml
            - tempo-data:/var/tempo

    grafana:
        image: grafana/grafana:latest
        volumes:
            - ./grafana/provisioning:/etc/grafana/provisioning
            - ./grafana-data:/var/lib/grafana
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_DISABLE_LOGIN_FORM=true
        ports:
            - "3000:3000"
        depends_on:
            - prometheus
            - loki
            - tempo

    promtail:
        image: grafana/promtail:latest
        volumes:
            - ./promtail-config.yml:/etc/promtail/config.yml
            - /var/run/docker.sock:/var/run/docker.sock:ro
        command: -config.file=/etc/promtail/config.yml
        depends_on:
            - loki

volumes:
    loki-data:
    tempo-data:
    prometheus-data:
