auth_enabled: false

server:
    http_listen_port: 3100

common:
    path_prefix: /loki
    replication_factor: 1
    ring:
        kvstore:
            store: inmemory

ingester:
    lifecycler:
        ring:
            kvstore:
                store: inmemory
        final_sleep: 0s
    chunk_idle_period: 5m
    chunk_retain_period: 30s

schema_config:
    configs:
        - from: "2025-01-23"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
              prefix: loki_index_
              period: 24h

storage_config:
    tsdb_shipper:
        active_index_directory: /loki/tsdb-index-active
        cache_location: /loki/tsdb-cache

limits_config:
    allow_structured_metadata: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h

compactor:
    working_directory: /loki/compactor

table_manager:
    retention_deletes_enabled: false
    retention_period: 0s
